#!/bin/bash
#SBATCH -n 1
#SBATCH --output=outputs/slurm/job_%j.out
#SBATCH --error=outputs/slurm/job_%j.err

# I run this in the SCC-CONNECT root folder

FILENAME="MFC_RUN"
DESCRIPTION="$FILENAME"

RUN_ROOT="${SLURM_SUBMIT_DIR}"
OUTPUT=$RUN_ROOT/outputs

echo "$SLURM_JOB_ID : $DESCRIPTION" >> $OUTPUT/descriptions.txt

OUTDIR=$OUTPUT/$FILENAME
mkdir -p $OUTDIR

module load gnu13 cmake
module load openmpi5

cd libs/clone/MFC
echo "Running using mpirun with $SLURM_NTASKS tasks"
./mfc.sh run examples/3D_IGR_jet/case.py --case-optimization -n $SLURM_NTASKS --binary mpirun
